#!/bin/bash

#########################################################
# Allows tmux to keep ssh-agent through detached sessions
SOCK=~/.ssh/ssh_auth_sock

if test -z "$TMUX"
then
    if test ! -z "$SSH_TTY"
    then
        if test "$SSH_AUTH_SOCK" && [ $SSH_AUTH_SOCK != $SOCK ]
        then
            ln -sf $SSH_AUTH_SOCK $SOCK
            export SSH_AUTH_SOCK=$SOCK
        fi
    fi
fi
#########################################################
